### ISSUE TITLE
ERROR/sl4a.FileUtils:121(2049): Failed to create directory.

### ISSUE THREAD

**Issue by damonkohler** [damonkohler/sl4a#159]
_From @GoogleCodeExporter on May 31, 2015 11:29_

```
What device(s) are you experiencing the problem on?
miumiu 9 (android 2.1)

What firmware version are you running on the device?


What steps will reproduce the problem?
1. install sl4a_r3.apk using adb
2. try to run it
3.

What is the expected output? What do you see instead?
Logcat
03-17 20:19:58.676: VERBOSE/sl4a.FileUtils:119(2049): Creating directory: 
scripts
03-17 20:19:58.676: ERROR/sl4a.FileUtils:121(2049): Failed to create directory.
03-17 20:19:58.676: DEBUG/AndroidRuntime(2049): Shutting down VM
03-17 20:19:58.676: WARN/dalvikvm(2049): threadid=3: thread exiting with 
uncaught exception (group=0x4001b168)
03-17 20:19:58.686: ERROR/AndroidRuntime(2049): Uncaught handler: thread main 
exiting due to uncaught exception
03-17 20:19:58.696: ERROR/AndroidRuntime(2049): java.lang.RuntimeException: 
Unable to start activity 
ComponentInfo{com.googlecode.android_scripting/com.googlecode.android_scripting.
activity.ScriptManager}: java.lang.RuntimeException: Failed to create scripts 
directory.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
        at android.app.ActivityThread.access$2200(ActivityThread.java:119)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4363)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.RuntimeException: Failed to create scripts directory.
        at com.googlecode.android_scripting.activity.ScriptManager.onCreate(ScriptManager.java:112)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
        ... 11 more


What version of the product are you using? On what operating system?


Please provide any additional information below.

I unmounted the SD just in case 
```

Original issue reported on code.google.com by `scottbur...@gmail.com` on 17 Mar 2011 at 8:23

_Copied from original issue: damonkohler/android-scripting#532_

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:29_

```
Ok.  Looks like the device does not have an SD card just internal memory.  Does 
it work without an SD card?
```

Original comment by `scottbur...@gmail.com` on 17 Mar 2011 at 8:30

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:29_

```
I'm on a droid 2 which DOES have an SD card and I'm getting this exact same 
error, rendering the software unusable. What gives?
```

Original comment by `robin.n....@gmail.com` on 31 Mar 2011 at 10:21

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:29_

```
Try manually creating /sdcard/sl4a/scripts
Remember to check permissions.
```

Original comment by `rjmatthews62` on 31 Mar 2011 at 10:23

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:29_

```
I get this message too on sl4a_r4.apk.  What's weird is that it doesn't seem to 
matter.  The /sdcard/sl4a/scripts directory is there.  It's empty which I 
assume is normal until you install a language like Python, etc.  I get the same 
exact behavior (except for the error message) when I install sl4a_r3.apk from 
scratch.
```

Original comment by `KenFehl...@gmail.com` on 18 Jun 2011 at 11:11

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:29_

```
This should be fixed (or at least, a more meaningful error message should 
appear) in R5.
```

Original comment by `rjmatthews62` on 25 Mar 2012 at 11:27
* Changed state: **Started**

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:29_

```
Still broken in r5
```

Original comment by `warelock...@gmail.com` on 12 Jun 2012 at 5:16
