### ISSUE TITLE
full screen error in terminal when JRuby starts

### ISSUE THREAD

**Issue by damonkohler** [damonkohler/sl4a#164]
_From @GoogleCodeExporter on May 31, 2015 11:28_

```
What device(s) are you experiencing the problem on?

  Motorola Cliq MB200

What firmware version are you running on the device?

  1.5

What steps will reproduce the problem?
1. Write a Ruby script.
2. Select the "Save & Run" button.
3. Observe error output in the terminal.

What is the expected output? What do you see instead?

  I would expect a clean terminal, except for my script's output (including any errors my script might produce if it has a bug, naturally).  What I see instead is a crapton of error output, followed by my script's output:

java.lang.ArrayIndexOutOfBoundsException
        at java.util.HugeEnumSet$HugeEnumSetIterator.next(HugeEnumSet.java:102)
        at java.util.HugeEnumSet$HugeEnumSetIterator.next(HugeEnumSet.java:52)
        at com.kenai.constantine.platform.ConstantResolver.getConstant(ConstantResolver.java:107)
        at com.kenai.constantine.platform.ConstantResolver.intValue(ConstantResolver.java:146)
        at com.kenai.constantine.platform.Errno.value(Errno.java:93)
        at org.jruby.Ruby.initErrno(Ruby.java:1312)
        at org.jruby.Ruby.initExceptions(Ruby.java:1283)
        at org.jruby.Ruby.bootstrap(Ruby.java:1028)
        at org.jruby.Ruby.init(Ruby.java:1005)
        at org.jruby.Ruby.newInstance(Ruby.java:173)
        at org.jruby.Main.run(Main.java:206)
        at org.jruby.Main.run(Main.java:117)
        at org.jruby.Main.main(Main.java:97)
        at dalvik.system.NativeStart.main(Native Method)

What version of the product are you using? On what operating system?

  SL4A r3 on Android 1.5

Please provide any additional information below.

```

Original issue reported on code.google.com by `apotheon` on 4 Mar 2011 at 5:01

_Copied from original issue: damonkohler/android-scripting#526_

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:28_

```
This error is mentioned in the article "Try the SL4A scripting environment for 
your Android device", at:

    http://www.techrepublic.com/blog/programming-and-development/try-the-sl4a-scripting-environment-for-your-android-device/3932
```

Original comment by `apotheon` on 4 Mar 2011 at 5:08
