### ISSUE TITLE
MS Exchange contacts cannot be retrieved. dd

### ISSUE THREAD

**Issue by damonkohler** [damonkohler/sl4a#199]
_From @GoogleCodeExporter on May 31, 2015 11:28_

```
What device(s) are you experiencing the problem on?
HTC Hero

What firmware version are you running on the device?
Android 2.2

What steps will reproduce the problem?
1. Starting sl4a.
2. Running "command.py" in terminal to get list of contacts stored on the phone 
(Only MS Exchange contact are available on the phone).

What is the expected output? What do you see instead?
Number of available contacts.
result=0

What version of the product are you using? On what operating system?
sl4a r2

Please provide any additional information below.

content of command.py:

##############
import android
droid = android.Android()

contactList = droid.ContactsGetCount()
print contactList
##########

tried:
contactsGet
contactsGetById
contactsGetCount 
as well but still result=0

discussion related to this issue
http://groups.google.com/group/android-scripting/browse_thread/thread/3e14c4ad6d
fda815

Logcat attached.

Cheers,
Pi3cH


```

Original issue reported on code.google.com by `mr.ped...@gmail.com` on 16 Oct 2010 at 11:33

Attachments:
* [logcat.txt](https://storage.googleapis.com/google-code-attachments/android-scripting/issue-460/comment-0/logcat.txt)

_Copied from original issue: damonkohler/android-scripting#460_

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:28_

```
The same here running Perl LWP::UserAgent  

Dalvik LogCat:

E/sl4a.Relay:157( 3694): java.io.IOException: session closed
E/sl4a.Relay:157( 3694): 	at 
org.connectbot.transport.ProcessTransport.read(ProcessTransport.java:81)
E/sl4a.Relay:157( 3694): 	at org.connectbot.service.Relay.run(Relay.java:125)
E/sl4a.Relay:157( 3694): 	at java.lang.Thread.run(Thread.java:1096)

Perl/SL4A error message:
501 Protocol scheme 'http' is not supported

```

Original comment by `rbsnk...@gmail.com` on 8 May 2011 at 3:48
