### ISSUE TITLE
xmlrpmlib

### ISSUE THREAD

**Issue by damonkohler** [damonkohler/sl4a#32]
_From @GoogleCodeExporter on May 31, 2015 11:31_

```
What device(s) are you experiencing the problem on?
Pantech Marauder from Verizon

What firmware version are you running on the device?
4.0.3

What steps will reproduce the problem?
Run the following code (with or without a running http server):
import xmlrpclib
xmlrpmlib.ServerProxy("http://192.168.1.179:8000").test()

What is the expected output? What do you see instead?
Expected output depends on xmlrpc server. Instead I get this stack trace:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    print server.raw_input("Name: ")
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/xmlrpclib.py", line 1224, in __call__
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/xmlrpclib.py", line 1575, in __request
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/xmlrpclib.py", line 1264, in request
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/xmlrpclib.py", line 1292, in single_request
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/xmlrpclib.py", line 1439, in send_content
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/httplib.py", line 951, in endheaders
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/httplib.py", line 811, in _send_output
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/httplib.py", line 773, in send
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/httplib.py", line 754, in connect
  File "/Users/hyan/Documents/qpyapp/python-for-android/build/python-install/lib/python2.7/socket.py", line 571, in create_connection
socket.error: [Errno 113] No route to host

What version of the product are you using? On what operating system?
I'm using the latest version (as of 5/24/13) from the Google Play Store.

Please provide any additional information below.
I can connect to the server with httplib without a problem, which is weird 
because the stack trace shows httplib throwing the exception.
```

Original issue reported on code.google.com by `a.haigh...@gmail.com` on 25 May 2013 at 8:12

_Copied from original issue: damonkohler/android-scripting#687_

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:31_

```
It turns out I had a networking error (misconfigured router), everything works 
now.
```

Original comment by `a.haigh...@gmail.com` on 25 May 2013 at 10:33
