### ISSUE TITLE
beanshell interpreter crashes

### ISSUE THREAD

**Issue by damonkohler** [damonkohler/sl4a#39]
_From @GoogleCodeExporter on May 31, 2015 11:31_

```
Samsung Galaxy S III SGH-T999

Cyanogenmod 10

What steps will reproduce the problem?

1. Get the beanshell addon.
2. Tap Install.
3. In SL4A, start a beanshell interpreter.

What is the expected output? What do you see instead?

Expected: Beanshell starts.

Observed: Beanshell crashes, failing to find the Interpreter class.

What version of the product are you using? On what operating system?

Latest, on Android 4.2.2 Jelly Bean.

```

Original issue reported on code.google.com by `andrew.p...@gmail.com` on 12 Apr 2013 at 12:09

_Copied from original issue: damonkohler/android-scripting#680_

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:31_

```
Also happens on CM 7.2.0. I tried to install other versions to see if it is 
just this version that is broken, but r1, r2, and r3 all install BeanShell 
2.0b4. r2 is the featured/default, but the other two seem to be the same 
version.

This is the output I get when attempting to run hello_world.bsh or just the 
interactive interpreter:

java.lang.ClassNotFoundException: bsh.Interpreter
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:234)
        at java.lang.Class.forName(Class.java:181)
        at com.android.internal.util.WithFramework.main(WithFramework.java:36)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoClassDefFoundError: bsh.Interpreter
        ... 5 more
Caused by: java.lang.ClassNotFoundException: bsh.Interpreter in loader 
dalvik.system.PathClassLoader[/mnt/sdcard/com.googlecode.bshforandroid/extras/bs
h/bsh-2.0b4-dx.jar]
        at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        ... 5 more
```

Original comment by `james.r.haigh` on 10 Jan 2014 at 2:26

**Comment by damonkohler** [comment]
_From @GoogleCodeExporter on May 31, 2015 11:31_

```
Ok
```

Original comment by `jokoswt@gmail.com` on 10 Jan 2014 at 3:38
